### PR TITLE
Create jakarta artifact replacing javax.json with jakarta.json

### LINKED ISSUE #6: Using/supporting Jakarta JSONP implementation
Hi!
Do you plan to support [Jakarta JSON Processing](https://eclipse-ee4j.github.io/jsonp/)? 

The JavaEE packages are now being maintained and developed by the Jakarta project and Jakarta JSON v2.0.0 has been released recently. Unfortunately, v2.0.0 is not backwards compatible with 1.x.x because of package name change.

### PR DESCRIPTION
**Pull request by fwiesweg**
Fixes #6.

This is an alternative solution to the problem, using postprocessing of the class files using the maven-shade-plugin as applied by jackson-jaxrs-providers.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you! That looks good, and I'd be happy to merge it.

Before merging there is just one process thing: I'd need a CLA (unless I have gotten one earlier at some point -- only needs to be done once before the first merged PR).
CLA doc is here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual mechanism is to print it, fill & sign, scan/photo, email to `info` fasterxml dot com.
Once I get it I'll store it and merge this PR.

Looking forward to merging!

**Comment by cowtowncoder** [comment]
CLA received, merged. Will backport in 2.12 branch for 2.12.2.

**Comment by cowtowncoder** [comment]
Alas, need to revert; 2.12.2 release broke due to... something.

**Comment by fwiesweg** [comment]
Sure, I'm not in a hurry to get this out of the door. Anything I can do?

**Comment by cowtowncoder** [comment]
@fwiesweg I think we are ok -- I ended up instead merging #10 to get the similar end result, but instead of using classifier, there's separate artifact (`jackson-datatype-jakarta-jsonp`). There's now some code duplication but number of classes is small so I am not very worried; and for 3.0 at least we may want to drop `jsr-353` module (TBD what to do with 2.x, at least after 2.13).

Still need to figure out what's wrong with classifier approach as that is needed for JAX-RS, but in short term I think this repo will get by without solving that. I do hope 2.12.2/jackson-datatype-jsr353 artifact can be corrected by sonatype admins tho.

**Pull request merged**
